name: Setup GCP
description: Setup gcloud, docker
inputs:
  workload_identity_provider:
    required: true
    description: GCP workload_identity_provider
  service_account:
    required: true
    description: GCP service account key
runs:
  using: composite
  steps:
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: nimil-base

    - name: GCP Authenticate
      id: auth
      uses: google-github-actions/auth@v0.4.1
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Configure docker
      shell: bash
      run: |
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev
