name: Setup kubectl
description: Setup kubectl for live01
inputs:
  workload_identity_provider:
    required: true
    description: GCP workload_identity_provider
  service_account:
    required: true
    description: GCP service account key
runs:
  using: composite
  steps:
    - name: GCP Authenticate
      id: auth
      uses: google-github-actions/auth@v0.4.1
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master

    - name: Configure docker
      shell: bash
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev
        gcloud container clusters get-credentials live01 --zone asia-northeast1-a --project nimil-base

    - name: Install Kubectl
      shell: bash
      run: |
        curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install kubectl /usr/local/bin/
