name: Deploy to Staging

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE: asia-northeast1-docker.pkg.dev/nimil-base/create-one/api:${{ github.ref_name }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup kubectl
        uses: ./.github/actions/kubectl
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Build and Push Image
        run: |
          docker build . -t $IMAGE

          docker push $IMAGE

      - name: Deploy
        run: |
          kubectl set image deployment/create-one-api-stg create-one-api=$IMAGE
