name: Deploy to Development

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - "doc/**"

env:
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/create-one-api
  LATEST_IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/create-one-api:${{ github.SHA }}
  TAGGED_IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/create-one-api:${{ github.SHA }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/kubectl
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Image
        run: |
          docker build . -t $LATEST_IMAGE

          docker tag $LATEST_IMAGE $TAGGED_IMAGE

          docker push $LATEST_IMAGE
          docker push $TAGGED_IMAGE

      - name: Deploy
        run: |
          kubectl set image deployment/create-one-api-dev create-one-api=$TAGGED_IMAGE
