name: Deploy to Staging

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE: asia-northeast1-docker.pkg.dev/nimil-base/createone/api:${{ github.ref_name }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud
        uses: ./.github/actions/gcloud
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Build and Push Image
        run: |
          docker build . -t $IMAGE

          docker push $IMAGE

      - name: Deploy
        run: |
          gcloud run deploy createone-api-stg \
              --image $IMAGE \
              --project ${{ secrets.GCP_PROJECT_ID }} \
              --region ${{ secrets.GCP_REGION }} \
              --platform=managed \
              --allow-unauthenticated \
              --quiet
