name: Deploy to Staging

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/create-one-api:${{ github.ref_name }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/kubectl
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Image
        run: |
          docker build . -t $IMAGE

          docker push $IMAGE

      - name: Deploy
        run: |
          kubectl set image deployment/create-one-api-stg create-one-api=$IMAGE
