name: Deploy to Development

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - "doc/**"

env:
  LATEST_IMAGE: asia-northeast1-docker.pkg.dev/nimil-base/create-one/api:latest
  TAGGED_IMAGE: asia-northeast1-docker.pkg.dev/nimil-base/create-one/api:${{ github.SHA }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup kubectl
        uses: ./.github/actions/kubectl
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Build and Push Image
        run: |
          docker build . -t $LATEST_IMAGE
          docker push $LATEST_IMAGE

          docker tag $LATEST_IMAGE $TAGGED_IMAGE
          docker push $TAGGED_IMAGE

      - name: Deploy
        run: |
          gcloud run deploy create-one-api-dev \
              --image $TAGGED_IMAGE \
              --port $PORT \
              --project $GCP_PROJECT_ID \
              --region $GCP_REGION \
              --platform=managed \
              --allow-unauthenticated \
              --quiet
