name: Deploy to Development

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "doc/**"

env:
  IMAGE: asia-northeast1-docker.pkg.dev/nimil-base/createone/api
  TAGGED_IMAGE: asia-northeast1-docker.pkg.dev/nimil-base/createone/api:${{ github.SHA }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud
        uses: ./.github/actions/gcloud
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Build and Push Image
        run: |
          docker build . -t "$IMAGE:dev"
          docker push "$IMAGE:dev"

          docker tag "$IMAGE:dev" "$IMAGE:latest"
          docker push "$IMAGE:latest"

      - name: Deploy
        run: |
          gcloud run deploy createone-api-dev \
              --image "$IMAGE:${{ github.SHA }}" \
              --project ${{ secrets.GCP_PROJECT_ID }} \
              --region ${{ secrets.GCP_REGION }} \
              --ingress all \
              --platform=managed \
              --allow-unauthenticated \
              --quiet
